version: '3'
services:
  webserver:
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ./dbt:/usr/local/airflow/dbt
      - ./drivers:/opt/airflow/drivers
      - ./data:/usr/local/airflow/data  
  scheduler:
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ./dbt:/usr/local/airflow/dbt
      - ./drivers:/opt/airflow/drivers
      - ./data:/usr/local/airflow/data 
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres_data  
      POSTGRES_USER: postgres       
      POSTGRES_PASSWORD: postgres   
    ports:
      - "5433:5432"                     
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - drivers:/opt/airflow/drivers 